version: 2.1
jobs:
  run_unit_tests:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit tests
          command: nix develop --command zig build test --summary all
  benchmark:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Benchmark eth-zvm
          command: |
            nix develop --command bash -c \
              'zig build -Doptimize=ReleaseFast --verbose'
            nix develop --command bash -c \
              'dev-scripts/benchmark-all-inputs ./zig-out/bin/eth-zvm 30'
      - persist_to_workspace:
          root: ./
          paths:
            - ./benchmarks/*.benchmark
  benchmark_evm:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Download official evm implementation
          command: ./dev-scripts/download-evm
      - run:
          name: Benchmark evm
          command: dev-scripts/benchmark-all-inputs ./evm 30
      - persist_to_workspace:
          root: ./
          paths:
            - ./benchmarks/*.benchmark
      - run:
          name: Disassemble bytecode
          command: ./evm disasm testdata/return-single-byte.bytecode
  make_benchmark_graph:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - store_artifacts:
          path: benchmarks/
workflows:
  version: 2
  test-deploy:
    jobs:
      - run_unit_tests
      - benchmark
      - benchmark_evm
      - make_benchmark_graph:
          requires:
            - benchmark
            - benchmark_evm
