version: 2.1
jobs:
  run_unit_tests:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit tests
          command: nix develop --command zig build test --summary all
  benchmark:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Benchmark eth-zvm
          command: |
            for i in $(seq 1 10);
            do
              nix develop --command bash -c 'xxd -r -p < testdata/return-single-byte.bytecode \
                | zig build run -Doptimize=ReleaseFast' \
                | grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append eth-zvm.benchmark
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./eth-zvm.benchmark
  benchmark_evm:
    docker:
      - image: cimg/base:2024.01
    environment:
      GETH_VERSION: 1.13.12-02eb36af
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Download official evm implementation
          command: |
            VERSION_BASE="geth-alltools-linux-amd64-${GETH_VERSION}"
            curl --location "https://gethstore.blob.core.windows.net/builds/${VERSION_BASE}.tar.gz" \
              | tar -zxvf - --strip-components 1 "${VERSION_BASE}/evm"
      - run:
          name: Benchmark evm
          command: |
            for i in $(seq 1 10);
            do
              ./evm run --codefile testdata/return-single-byte.bytecode --statdump \
                |& grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append evm.benchmark
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./evm.benchmark
      - run:
          name: Disassemble bytecode
          command: ./evm disasm testdata/return-single-byte.bytecode
  make_benchmark_graph:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - store_artifacts:
          path: benchmarks.html
      - store_artifacts:
          path: eth-zvm.benchmark
      - store_artifacts:
          path: evm.benchmark
workflows:
  version: 2
  test-deploy:
    jobs:
      - run_unit_tests
      - benchmark
      - benchmark_evm
      - make_benchmark_graph:
          requires:
            - benchmark
            - benchmark_evm
