version: 2.1
jobs:
  run_unit_tests:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit tests
          command: nix develop --command zig build test --summary all
  benchmark:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Benchmark eth-zvm
          command: nix develop --command bash -c 'xxd -r -p < testdata/return-single-byte.bytecode | zig build run -Doptimize=ReleaseFast' | tee /tmp/output
      - run:
          name: Extract runtime from output
          command: cat /tmp/output | grep -oP 'execution time:\s+\K\d+\.\d+' | tee eth-zvm.benchmark
      - persist_to_workspace:
          root: ./
          paths:
            - ./eth-zvm.benchmark
  benchmark_evm:
    docker:
      - image: cimg/base:2024.01
    environment:
      GETH_VERSION: 1.13.12-02eb36af
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Download official evm implementation
          command: |
            VERSION_BASE="geth-alltools-linux-amd64-${GETH_VERSION}"
            curl --location "https://gethstore.blob.core.windows.net/builds/${VERSION_BASE}.tar.gz" \
              | tar -zxvf - --strip-components 1 "${VERSION_BASE}/evm"
      - run:
          name: Benchmark evm
          command: ./evm run --codefile testdata/return-single-byte.bytecode --statdump | tee /tmp/output
      - run:
          name: Extract runtime from output
          command: cat /tmp/output | grep -oP 'execution time:\s+\K\d+\.\d+' |& tee evm.benchmark
      - persist_to_workspace:
          root: ./
          paths:
            - ./evm.benchmark
      - run:
          name: Disassemble bytecode
          command: ./evm disasm testdata/return-single-byte.bytecode
workflows:
  version: 2
  test-deploy:
    jobs:
      - run_unit_tests
      - benchmark
      - benchmark_evm
