version: 2.1
jobs:
  run_unit_tests:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit tests
          command: nix develop --command zig build test --summary all
  benchmark:
    docker:
      - image: nixos/nix:2.15.0
    steps:
      - run:
          name: Enable Nix flakes
          command: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Benchmark eth-zvm
          command: |
            for i in $(seq 1 30);
            do
              nix develop --command bash -c 'xxd -r -p < testdata/return-single-byte.bytecode \
                | zig build run -Doptimize=ReleaseFast' \
                | grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/eth-zvm_single-byte.benchmark
              nix develop --command bash -c 'xxd -r -p < testdata/return-32-byte.bytecode \
                | zig build run -Doptimize=ReleaseFast' \
                | grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/eth-zvm_32-byte.benchmark
              nix develop --command bash -c 'xxd -r -p < testdata/count-to-1000-by-1.bytecode \
                | zig build run -Doptimize=ReleaseFast' \
                | grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/eth-zvm_count-to-1000-by-1.benchmark
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./benchmarks/eth-zvm_single-byte.benchmark
            - ./benchmarks/eth-zvm_32-byte.benchmark
            - ./benchmarks/eth-zvm_count-to-1000-by-1.benchmark
  benchmark_evm:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Download official evm implementation
          command: ./dev-scripts/download-evm
      - run:
          name: Benchmark evm
          command: |
            for i in $(seq 1 30);
            do
              ./evm run --codefile testdata/return-single-byte.bytecode --statdump \
                |& grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/evm_single-byte.benchmark
              ./evm run --codefile testdata/return-32-byte.bytecode --statdump \
                |& grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/evm_32-byte.benchmark
              ./evm run --codefile testdata/count-to-1000-by-1.bytecode --statdump \
                |& grep -oP 'execution time:\s+\K\d+\.\d+' \
                | tee --append benchmarks/evm_count-to-1000-by-1.benchmark
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./benchmarks/evm_single-byte.benchmark
            - ./benchmarks/evm_32-byte.benchmark
            - ./benchmarks/evm_count-to-1000-by-1.benchmark
      - run:
          name: Disassemble bytecode
          command: ./evm disasm testdata/return-single-byte.bytecode
  make_benchmark_graph:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - store_artifacts:
          path: benchmarks/
workflows:
  version: 2
  test-deploy:
    jobs:
      - run_unit_tests
      - benchmark
      - benchmark_evm
      - make_benchmark_graph:
          requires:
            - benchmark
            - benchmark_evm
